### ISSUE TITLE
Thread refresh issue

### ISSUE THREAD

**Issue by trystant** [hentschellj/game-forum#2]
Once logged in, if the user refreshes the screen, an error appears on the browser page
![screenshot 2018-03-05 at 14 13 13](https://user-images.githubusercontent.com/13509/36994612-a74eee46-207f-11e8-828f-cfe2d0c237c4.png)

The source of this isn't clear, but a couple of measures that can be taken to resolve this include:
- [ ] Adding error handling to the `/auth/refresh` endpoint to get the details on what exactly has gone wrong
- [x] Check the node console logs in development for `/auth/refresh`
- [ ] Put together an automated test to determine 

The error message is:
```
Error: Unknown authentication strategy "jwt"
    at attempt (C:\Projects\game-forum-backend\node_modules\passport\lib\middleware\authenticate.js:186:37)
    at authenticate (C:\Projects\game-forum-backend\node_modules\passport\lib\middleware\authenticate.js:362:7)
    at Layer.handle [as handle_request] (C:\Projects\game-forum-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Projects\game-forum-backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Projects\game-forum-backend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Projects\game-forum-backend\node_modules\express\lib\router\layer.js:95:5)
    at C:\Projects\game-forum-backend\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Projects\game-forum-backend\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Projects\game-forum-backend\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\Projects\game-forum-backend\node_modules\body-parser\lib\types\json.js:118:7)
    at Layer.handle [as handle_request] (C:\Projects\game-forum-backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Projects\game-forum-backend\node_modules\express\lib\router\index.js:317:13)
    at C:\Projects\game-forum-backend\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Projects\game-forum-backend\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Projects\game-forum-backend\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Projects\game-forum-backend\node_modules\express\lib\router\index.js:174:3)
```

**Comment by trystant** [comment]
Moving this to hentschellj/game-forum-backend
